version: '3'
services:
  nginx:
    image: nginx:1.17.9
    restart: on-failure:3
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ./src:/var/www:delegated
      - ./config/default.dev.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php
    networks:
      - app-network
  # elasticsearch:
  #   image: elasticsearch:6.5.4
  #   container_name: elasticsearch
  #   networks:
  #     - app-network
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure:3
    volumes:
      - ./src:/var/www:delegated
    # ports:
    #   - 9000:9000
    networks:
      - app-network
      
  redis:
    image: redis:4.0-alpine
    restart: on-failure:3
    # command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    expose:
      - 6379
    volumes:
      - redisdata:/data
    networks:
      - app-network
    restart: on-failure:3

volumes:
  redisdata:
    driver: local
  # lumendata:
  #   drive: local

networks:
  app-network:
    driver: bridge


   
